**This notebook about computer vision models with PyTorch**

In [1]:
import torch
import torchvision
torch.cuda.is_available()

True

**Working with tensors**

In [2]:
# define tensor wit default data type
x = torch.ones (2, 2)
print (x)
print (x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [3]:
# specify data type
x = torch.ones (2, 2, dtype = torch.int8)
print (x)
print (x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)
torch.int8


In [4]:
# change tensor data type
x = torch.ones (1, dtype = torch.uint8)

print (x.dtype)

x = x.type (torch.float)
print (x.dtype)

torch.uint8
torch.float32


In [5]:
# converting tensors to NumPy arrays
x = torch.rand (2, 2)
print (x)
print (x.dtype)

y = x.numpy ()
print (y)
print (y.dtype)

tensor([[0.1420, 0.0595],
        [0.7709, 0.4668]])
torch.float32
[[0.14203298 0.05945039]
 [0.7709309  0.46678817]]
float32


In [6]:
# converting NumPy arrays to tensors
import numpy as np

x = np.zeros ((2, 2), dtype = np.float32)
print (x)
print (x.dtype)

y = torch.from_numpy (x)
print (x)
print (y.dtype)

[[0. 0.]
 [0. 0.]]
float32
[[0. 0.]
 [0. 0.]]
torch.float32
